### ISSUE TITLE
【强哥👍】脚本支持自定义目标路径 

### ISSUE THREAD

**Issue by TOPWN** [chiclaim/GitRepos#1]

**Comment by TOPWN** [comment]
`python repos.py sync`是将代码拉取到默认路径`target_path = get_parent_dir()`，可以根据输入的路径参数自定义目标路径吗？

**Comment by chiclaim** [comment]
@TOPWN 这个功能没加，如果将代码拉去到自定义路径的话，那所有命令都需要加上路径了。直接将脚本拷贝到项目的主工程，然后就会在主工程的平级目录拉去所有模块。
